import "@/styles/tailwind.css";
import Link from "next/link";

export const metadata = {
	title: "NextJS link test",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const navLinks = [
		{ name: "Home", href: "/" },
		{ name: "TestPage", href: "/test" },
	];

	return (
		<html lang="en">
			<body className="w-full">
				<div className="navbar bg-base-100 w-full px-4">
					<span className="normal-case text-xl">LinkTest</span>
					<div className="navbar-end flex gap-8 w-full">
						{navLinks.map((current, indx) => {
							return (
								<Link
									key={indx}
									href={current.href}
									className="font-bold px-3 py-2 border border-white rounded-xl hover:bg-[rgba(255,255,255,0.15)] transition-all antialiased duration-500"
								>
									{current.name}
								</Link>
							);
						})}
					</div>
				</div>
				{children}
			</body>
		</html>
	);
}
